//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClientResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.ClientResources", typeof(ClientResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application submitted..
        /// </summary>
        internal static string ApplicationSubmittedMessage {
            get {
                return ResourceManager.GetString("ApplicationSubmittedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which tender do you want to apply to? (number, or press Enter to skip).
        /// </summary>
        internal static string ApplyToTenderPrompt {
            get {
                return ResourceManager.GetString("ApplyToTenderPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press Esc to cancel waiting and return to the main menu..
        /// </summary>
        internal static string CancelWaitingHint {
            get {
                return ResourceManager.GetString("CancelWaitingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot invoke &apos;{0}&apos;: connection state = {1}.
        /// </summary>
        internal static string CannotInvokeError {
            get {
                return ResourceManager.GetString("CannotInvokeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot join game {0}. Shoot again!.
        /// </summary>
        internal static string CannotJoinGameError {
            get {
                return ResourceManager.GetString("CannotJoinGameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a name for your game:.
        /// </summary>
        internal static string ChooseGameNamePrompt {
            get {
                return ResourceManager.GetString("ChooseGameNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose your login:.
        /// </summary>
        internal static string ChooseLoginPrompt {
            get {
                return ResourceManager.GetString("ChooseLoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your company : {0}.
        /// </summary>
        internal static string CompanyAssignedFormat {
            get {
                return ResourceManager.GetString("CompanyAssignedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the name of the company:.
        /// </summary>
        internal static string CompanyNamePrompt {
            get {
                return ResourceManager.GetString("CompanyNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press Enter to confirm and submit..
        /// </summary>
        internal static string ConfirmSubmissionPrompt {
            get {
                return ResourceManager.GetString("ConfirmSubmissionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connected to the Hub: {0}.
        /// </summary>
        internal static string ConnectedToHubMessage {
            get {
                return ResourceManager.GetString("ConnectedToHubMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - {0} ({1}).
        /// </summary>
        internal static string ConsultantLineFormat {
            get {
                return ResourceManager.GetString("ConsultantLineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skills : {0}.
        /// </summary>
        internal static string ConsultantSkillsFormat {
            get {
                return ResourceManager.GetString("ConsultantSkillsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create your company.
        /// </summary>
        internal static string CreateCompanyHeader {
            get {
                return ResourceManager.GetString("CreateCompanyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tender applications.
        /// </summary>
        internal static string DecisionHeader {
            get {
                return ResourceManager.GetString("DecisionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✅ Decision (coming soon).
        /// </summary>
        internal static string DecisionPlaceholder {
            get {
                return ResourceManager.GetString("DecisionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have been disconnected from the lobby..
        /// </summary>
        internal static string DisconnectedFromLobbyMessage {
            get {
                return ResourceManager.GetString("DisconnectedFromLobbyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which training do you want to enroll in? (number, or press Enter to skip).
        /// </summary>
        internal static string EnrollInTrainingPrompt {
            get {
                return ResourceManager.GetString("EnrollInTrainingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enrollment submitted..
        /// </summary>
        internal static string EnrollmentSubmittedMessage {
            get {
                return ResourceManager.GetString("EnrollmentSubmittedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the number of the game you want to join: .
        /// </summary>
        internal static string EnterGameNumberPrompt {
            get {
                return ResourceManager.GetString("EnterGameNumberPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to connect to Hub: {0}. If the problem persists, please contact an administrator..
        /// </summary>
        internal static string FailedToConnectError {
            get {
                return ResourceManager.GetString("FailedToConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🧩 Game {0} created, waiting for other players....
        /// </summary>
        internal static string GameCreatedMessage {
            get {
                return ResourceManager.GetString("GameCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}. {1} ({2}/{3}).
        /// </summary>
        internal static string GameListItemFormat {
            get {
                return ResourceManager.GetString("GameListItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à __        ___             ____          ____            _                   _
        /// \ \      / / |__  _   _  / ___|  ___   / ___|  ___ _ __(_) ___  _   _ ___  | |
        ///  \ \ /\ / /| &apos;_ \| | | | \___ \ / _ \  \___ \ / _ \ &apos;__| |/ _ \| | | / __| | |
        ///   \ V  V / | | | | |_| |  ___) | (_) |  ___) |  __/ |  | | (_) | |_| \__ \ |_|
        ///    \_/\_/  |_| |_|\__, | |____/ \___/  |____/ \___|_|  |_|\___/ \__,_|___/ (_)
        ///                   |___/                                                       .
        /// </summary>
        internal static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🏁 Game over.
        /// </summary>
        internal static string GameOverHeader {
            get {
                return ResourceManager.GetString("GameOverHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thanks for playing! (final scoring not implemented yet).
        /// </summary>
        internal static string GameOverMessage {
            get {
                return ResourceManager.GetString("GameOverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///Games available:
        ///.
        /// </summary>
        internal static string GamesAvailableHeader {
            get {
                return ResourceManager.GetString("GamesAvailableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🚀 The Game {0} starts!.
        /// </summary>
        internal static string GameStartingMessage {
            get {
                return ResourceManager.GetString("GameStartingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Good bye {0}! See you soon!..
        /// </summary>
        internal static string GoodbyeMessage {
            get {
                return ResourceManager.GetString("GoodbyeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HubException while invoking &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string HubExceptionError {
            get {
                return ResourceManager.GetString("HubExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your choice isn&apos;t valid..
        /// </summary>
        internal static string InvalidChoiceError {
            get {
                return ResourceManager.GetString("InvalidChoiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choice is invalid..
        /// </summary>
        internal static string InvalidChoiceMessage {
            get {
                return ResourceManager.GetString("InvalidChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid number..
        /// </summary>
        internal static string InvalidNumberError {
            get {
                return ResourceManager.GetString("InvalidNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid operation during &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string InvalidOperationError {
            get {
                return ResourceManager.GetString("InvalidOperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🔗 You have joined the game {0}.
        /// </summary>
        internal static string JoinedGameMessage {
            get {
                return ResourceManager.GetString("JoinedGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You left the game {0}..
        /// </summary>
        internal static string LeftGameMessageFormat {
            get {
                return ResourceManager.GetString("LeftGameMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main menu.
        /// </summary>
        internal static string MainMenuHeader {
            get {
                return ResourceManager.GetString("MainMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📊 Market analysis (coming soon).
        /// </summary>
        internal static string MarketAnalysisPlaceholder {
            get {
                return ResourceManager.GetString("MarketAnalysisPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Market.
        /// </summary>
        internal static string MarketHeader {
            get {
                return ResourceManager.GetString("MarketHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. Create a game.
        /// </summary>
        internal static string MenuOptionCreateGame {
            get {
                return ResourceManager.GetString("MenuOptionCreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Join a game.
        /// </summary>
        internal static string MenuOptionJoinGame {
            get {
                return ResourceManager.GetString("MenuOptionJoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3. Quit.
        /// </summary>
        internal static string MenuOptionQuit {
            get {
                return ResourceManager.GetString("MenuOptionQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Company : {0}.
        /// </summary>
        internal static string MyCompanyHeaderFormat {
            get {
                return ResourceManager.GetString("MyCompanyHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Company found.
        /// </summary>
        internal static string NoCompanyError {
            get {
                return ResourceManager.GetString("NoCompanyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No consultant selected..
        /// </summary>
        internal static string NoConsultantSelectedError {
            get {
                return ResourceManager.GetString("NoConsultantSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No decisions made this round..
        /// </summary>
        internal static string NoDecisionsMessage {
            get {
                return ResourceManager.GetString("NoDecisionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No consultant available to apply..
        /// </summary>
        internal static string NoFreeConsultantError {
            get {
                return ResourceManager.GetString("NoFreeConsultantError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No game available at this time..
        /// </summary>
        internal static string NoGamesAvailableMessage {
            get {
                return ResourceManager.GetString("NoGamesAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string NoSkillsLabel {
            get {
                return ResourceManager.GetString("NoSkillsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No tenders available this round..
        /// </summary>
        internal static string NoTendersMessage {
            get {
                return ResourceManager.GetString("NoTendersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not logged in.
        /// </summary>
        internal static string NotLoggedInLabel {
            get {
                return ResourceManager.GetString("NotLoggedInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No trainings available this round..
        /// </summary>
        internal static string NoTrainingsMessage {
            get {
                return ResourceManager.GetString("NoTrainingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}. {1} ({2}).
        /// </summary>
        internal static string NumberedConsultantLineFormat {
            get {
                return ResourceManager.GetString("NumberedConsultantLineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📨 {0} submitted their decisions..
        /// </summary>
        internal static string PlayerSubmittedFormat {
            get {
                return ResourceManager.GetString("PlayerSubmittedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Players ({0}/{1}) : {2}.
        /// </summary>
        internal static string PlayersWaitingPrompt {
            get {
                return ResourceManager.GetString("PlayersWaitingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press Enter to continue....
        /// </summary>
        internal static string PressEnterToContinuePrompt {
            get {
                return ResourceManager.GetString("PressEnterToContinuePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🔗 Reconnected!.
        /// </summary>
        internal static string ReconnectedMessage {
            get {
                return ResourceManager.GetString("ReconnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⚠️ Reconnecting....
        /// </summary>
        internal static string ReconnectingWarning {
            get {
                return ResourceManager.GetString("ReconnectingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⏳ Resolving the round (coming soon).
        /// </summary>
        internal static string ResolutionPlaceholder {
            get {
                return ResourceManager.GetString("ResolutionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}. Return to the main menu.
        ///.
        /// </summary>
        internal static string ReturnToMainMenuFormat {
            get {
                return ResourceManager.GetString("ReturnToMainMenuFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revenue : {0} €.
        /// </summary>
        internal static string RevenueFormat {
            get {
                return ResourceManager.GetString("RevenueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Round {0}/{1}.
        /// </summary>
        internal static string RoundHeaderFormat {
            get {
                return ResourceManager.GetString("RoundHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which consultant should be enrolled? (number).
        /// </summary>
        internal static string SelectConsultantPrompt {
            get {
                return ResourceManager.GetString("SelectConsultantPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which consultants should be assigned? (comma-separated numbers).
        /// </summary>
        internal static string SelectConsultantsPrompt {
            get {
                return ResourceManager.GetString("SelectConsultantsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [From the Server] {0}.
        /// </summary>
        internal static string ServerMessagePrefix {
            get {
                return ResourceManager.GetString("ServerMessagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🧮 Simulation (coming soon).
        /// </summary>
        internal static string SimulationPlaceholder {
            get {
                return ResourceManager.GetString("SimulationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  {0} ({1}).
        /// </summary>
        internal static string SkillWithLevelFormat {
            get {
                return ResourceManager.GetString("SkillWithLevelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Free.
        /// </summary>
        internal static string StatusFree {
            get {
                return ResourceManager.GetString("StatusFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à InTraining.
        /// </summary>
        internal static string StatusInTraining {
            get {
                return ResourceManager.GetString("StatusInTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On Mission.
        /// </summary>
        internal static string StatusOnMission {
            get {
                return ResourceManager.GetString("StatusOnMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Review your decisions.
        /// </summary>
        internal static string SubmissionHeader {
            get {
                return ResourceManager.GetString("SubmissionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📤 Submitting choices (coming soon).
        /// </summary>
        internal static string SubmissionPlaceholder {
            get {
                return ResourceManager.GetString("SubmissionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Applied to {0} with {1} consultant(s).
        /// </summary>
        internal static string TenderDecisionSummaryFormat {
            get {
                return ResourceManager.GetString("TenderDecisionSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}. {1} - {2} € - {3} round(s) - {4} consultant(s).
        /// </summary>
        internal static string TenderDetailFormat {
            get {
                return ResourceManager.GetString("TenderDetailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - {0} (budget {1} €).
        /// </summary>
        internal static string TenderLineFormat {
            get {
                return ResourceManager.GetString("TenderLineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à    Required: {0}.
        /// </summary>
        internal static string TenderRequiredSkillsFormat {
            get {
                return ResourceManager.GetString("TenderRequiredSkillsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tenders.
        /// </summary>
        internal static string TendersSectionHeader {
            get {
                return ResourceManager.GetString("TendersSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enrolled {0} in {1}.
        /// </summary>
        internal static string TrainingDecisionSummaryFormat {
            get {
                return ResourceManager.GetString("TrainingDecisionSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}. {1} - {2} - {3} € - {4} round(s).
        /// </summary>
        internal static string TrainingDetailFormat {
            get {
                return ResourceManager.GetString("TrainingDetailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trainings.
        /// </summary>
        internal static string TrainingsSectionHeader {
            get {
                return ResourceManager.GetString("TrainingsSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Treasury : {0} €.
        /// </summary>
        internal static string TreasuryFormat {
            get {
                return ResourceManager.GetString("TreasuryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unexpected error while sending &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Waiting for other players.
        /// </summary>
        internal static string WaitingAnimationLabel {
            get {
                return ResourceManager.GetString("WaitingAnimationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🕹 Waiting for game {0}.
        /// </summary>
        internal static string WaitingForGameHeader {
            get {
                return ResourceManager.GetString("WaitingForGameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⌛ Waiting for the other players....
        /// </summary>
        internal static string WaitingForOtherPlayersMessage {
            get {
                return ResourceManager.GetString("WaitingForOtherPlayersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🎮 Why So Serious!.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///Your choice:.
        /// </summary>
        internal static string YourChoicePrompt {
            get {
                return ResourceManager.GetString("YourChoicePrompt", resourceCulture);
            }
        }
    }
}
